Update deploy

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -56,6 +56,28 @@ then
     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
 
+# Initialize rbenv
+if command -v rbenv &> /dev/null; then
+  eval "$(rbenv init -)"
+fi
+
+# Ensure the correct Ruby version is being used
+rbenv shell 3.3.6
+
+# Check if Ruby is installed
+if ! command -v ruby &> /dev/null
+then
+    echo "Ruby could not be found. Please install Ruby and ensure it is in your PATH."
+    exit 1
+fi
+
+read -r -p "Do you want to proceed? [y/N] " response
+if [[ ! $response =~ ^([yY][eE][sS]|[yY])+$ ]]
+then
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+fi
+
 # # Check if there are any uncommitted changes
 # if ! git diff-index --quiet HEAD --; then
 #     echo "Changes to the following files are uncommitted:"
